/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package aula1109;

/**
 *
 * @author IFSP
 */
public class Testecarro {
    
    public static void main(String[] args) {
        Carro c1 = new Carro ("Passat", 50);
        c1.combustivelAtual ();
        
        c1.abastecer(20);
        c1.combustivelAtual ();
        
          c1.abastecer(10);
        c1.combustivelAtual ();
        
        
          c1.abastecer(20);
        c1.combustivelAtual ();
        
        
        
        
        
        
    } 
    
}
