
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author IFSP
 */
public class FormAlmoxarifado extends javax.swing.JFrame {

    /**
     * Creates new form FormAlmoxarifado
     */
    public FormAlmoxarifado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtMaterial = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtEstoqueMinimo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlmoxarifado = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnAdicionarEstoque = new javax.swing.JButton();
        btnRetiradaEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestão de Almoxarifado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Código do Material:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nome do Material:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Estoque:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Estoque Minímo:");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtMaterial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEstoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEstoqueMinimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblAlmoxarifado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Caixa Papel A4", "25", "10", "Ok"},
                {"2", "Cartucho Impressora", "15", "5", "Ok"},
                {"3", "Envelope timbrado", "15", "20", "Crítico"}
            },
            new String [] {
                "Código", "Número do Material", "Estoque", "Estoque Minímo", "Status Estoque"
            }
        ));
        jScrollPane1.setViewportView(tblAlmoxarifado);

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAdicionarEstoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdicionarEstoque.setText("Adicionar Estoque");
        btnAdicionarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEstoqueActionPerformed(evt);
            }
        });

        btnRetiradaEstoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRetiradaEstoque.setText("Retirada Estoque");
        btnRetiradaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiradaEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSalvar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEstoqueMinimo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdicionarEstoque)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetiradaEstoque))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnRetiradaEstoque)
                    .addComponent(btnAdicionarEstoque))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEstoqueActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblAlmoxarifado.getSelectedRow();
        int totalLinhas = tblAlmoxarifado.getRowCount();
        String status = "Ok";
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela");
        } else {
            String antigoEstoque = (String) tblAlmoxarifado.getValueAt(linhaSelecionada, 2);
            String novoEstoque = JOptionPane.showInputDialog("Informe a quantidade a ser adicionada: ");
            int anEstoque = Integer.parseInt(antigoEstoque);
            int noEstoque = Integer.parseInt(novoEstoque);

            noEstoque += anEstoque;
            String NovoEstoque = Integer.toString(noEstoque);

            tblAlmoxarifado.setValueAt(NovoEstoque, linhaSelecionada, 2);
            JOptionPane.showMessageDialog(this, "Estoque atualizado com sucesso!");
        }
        for (int i = 0; i < totalLinhas; i++) {
            String esto = tblAlmoxarifado.getValueAt(i, 2).toString();
            String minEsto = tblAlmoxarifado.getValueAt(i, 3).toString();
            int Esto = Integer.parseInt(esto);
            int MiniEsto = Integer.parseInt(minEsto);

            if (Esto >= MiniEsto) {
                tblAlmoxarifado.setValueAt(status, i, 4);
            } else {
                tblAlmoxarifado.setValueAt("Critico", i, 4);
            }
        }
    }//GEN-LAST:event_btnAdicionarEstoqueActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here: 
        String codigo = txtCodigo.getText();
        String material = txtMaterial.getText();
        String estoque = txtEstoque.getText();
        String minEstoque = txtEstoqueMinimo.getText();
        String status;
        int igual = 0;
        int totalLinhas = tblAlmoxarifado.getRowCount();

        for (int i = 0; i < totalLinhas; i++) {
            String strcod = tblAlmoxarifado.getValueAt(i, 0).toString();
            int matCodigo = Integer.parseInt(strcod);
            int codDado = Integer.parseInt(codigo);

            if (codDado == matCodigo) {
                igual = 1;
            }
        }

        if (igual == 1) {
            JOptionPane.showMessageDialog(this, "Código já existente!");
        } else {
            int Ess = Integer.parseInt(estoque);
        int MinEss = Integer.parseInt(minEstoque);
        if (Ess >= MinEss) {
            status = "Ok";
        } else {
            status = "Critico";
        }
            DefaultTableModel tabela = (DefaultTableModel) tblAlmoxarifado.getModel();
            Object[] novalinha = new Object[]{
                codigo, material, estoque, minEstoque, status
            };
            tabela.addRow(novalinha);
            JOptionPane.showMessageDialog(this, "Material adicionado com sucesso!", "Aviso", 1);
            txtCodigo.setText("");
            txtMaterial.setText("");
            txtEstoque.setText("");
            txtEstoqueMinimo.setText("");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblAlmoxarifado.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse material?", "Aviso!", 0, 1);
            if (confirm == 0) {
                DefaultTableModel tabela = (DefaultTableModel) tblAlmoxarifado.getModel();
                tabela.removeRow(linhaSelecionada);
                JOptionPane.showMessageDialog(this, "Material excluido com sucesso!");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRetiradaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiradaEstoqueActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblAlmoxarifado.getSelectedRow();
        int totalLinhas = tblAlmoxarifado.getRowCount();
        String status = "Ok";
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela");
        } else {
            String antigoEstoque = (String) tblAlmoxarifado.getValueAt(linhaSelecionada, 2);
            String retEstoque = JOptionPane.showInputDialog("Informe a quantidade a ser subtraída: ");
            int anEstoque = Integer.parseInt(antigoEstoque);
            int RetiradaEstoque = Integer.parseInt(retEstoque);
            
            if (RetiradaEstoque > anEstoque) {
                JOptionPane.showMessageDialog(this, "Quantidade insuficiente!");
            } else {
                anEstoque -= RetiradaEstoque;
                String NovoEstoque = Integer.toString(anEstoque);

                tblAlmoxarifado.setValueAt(NovoEstoque, linhaSelecionada, 2);
                JOptionPane.showMessageDialog(this, "Estoque atualizado com sucesso!");
            }
        }
        for (int i = 0; i < totalLinhas; i++) {
            String esto = tblAlmoxarifado.getValueAt(i, 2).toString();
            String minEsto = tblAlmoxarifado.getValueAt(i, 3).toString();
            int Esto = Integer.parseInt(esto);
            int MiniEsto = Integer.parseInt(minEsto);

            if (Esto >= MiniEsto) {
                tblAlmoxarifado.setValueAt(status, i, 4);
            } else {
                tblAlmoxarifado.setValueAt("Critico", i, 4);
            }
        }
    }//GEN-LAST:event_btnRetiradaEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlmoxarifado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlmoxarifado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEstoque;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRetiradaEstoque;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlmoxarifado;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtMaterial;
    // End of variables declaration//GEN-END:variables
}
